/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import javax.swing.JOptionPane;
import java.sql.*;


/**
 *
 * @author HP
 */
public class Booking extends javax.swing.JFrame {

    /**
     * Creates new form Booking
     */
    public Booking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        combox = new javax.swing.JComboBox();
        pack = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        packlb = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        memlbl = new javax.swing.JLabel();
        amtlbl = new javax.swing.JLabel();
        minus = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        memtxt = new javax.swing.JTextField();
        amttxt = new javax.swing.JTextField();
        userlb = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/web-banner2.png"))); // NOI18N
        jLabel8.setText("Proceed to payment");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        combox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select any one", "Family Combo", "College Days", "You are the king" }));
        combox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxActionPerformed(evt);
            }
        });
        getContentPane().add(combox, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 130, 140, 30));

        pack.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select any one", "Customised Package", "Packages" }));
        pack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packActionPerformed(evt);
            }
        });
        getContentPane().add(pack, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 150, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Add to cart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 320, 148, 45));

        packlb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        packlb.setForeground(new java.awt.Color(255, 255, 255));
        packlb.setText("Select a Package:");
        getContentPane().add(packlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 170, 43));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Choose packge type:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 202, 175, 43));

        memlbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        memlbl.setForeground(new java.awt.Color(255, 255, 255));
        memlbl.setText("Enter number of members:");
        getContentPane().add(memlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, -1, 31));

        amtlbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        amtlbl.setForeground(new java.awt.Color(255, 255, 255));
        amtlbl.setText("Amount of package:");
        getContentPane().add(amtlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, -1, 25));

        minus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        minus.setText("-");
        getContentPane().add(minus, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 180, -1, -1));

        plus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plus.setText("+");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });
        getContentPane().add(plus, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 180, -1, 34));
        getContentPane().add(memtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 180, 39, 33));
        getContentPane().add(amttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 230, 80, 30));
        getContentPane().add(userlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 100, 310, 29));

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("Proceed to Payment");
        jButton5.setToolTipText("");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, 190, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/web-banner2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 420));

        jMenu6.setText("<");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        jMenu4.setText("Home");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu1.setText("About Us");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Adventures");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Bookings");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu5.setText("Register");
        jMenu5.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                jMenu5MenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        jMenu7.setText("Offers");
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu7MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu7);

        jMenu8.setText("Combo Packages");
        jMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu8MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plusActionPerformed

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu6MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        new Welcome().setVisible(true);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        //new Adventure().setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        new booking1().setVisible(true);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu5MenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_jMenu5MenuKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5MenuKeyPressed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        new Signup().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MouseClicked
        // TODO add your handling code h0re:
        new Offers().setVisible(true);
    }//GEN-LAST:event_jMenu7MouseClicked

    private void jMenu8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu8MouseClicked
        // TODO add your handling code here:
        new Combo().setVisible(true);
    }//GEN-LAST:event_jMenu8MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        minus.setVisible(false);
        plus.setVisible(false);
                 amtlbl.setVisible(false);
             combox.setVisible(false);
             memlbl.setVisible(false);
             memtxt.setVisible(false);
             jButton1.setVisible(false);
             
             memlbl.setVisible(false);
             amtlbl.setVisible(false);
             amttxt.setVisible(false);
             minus.setVisible(false);
             packlb.setVisible(false);
             jButton5.setVisible(false);
             try{
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","chinmay","chinmay99");
            Statement stmt=con.createStatement();
            String query="Select * from userlogin;";
            ResultSet rs=stmt.executeQuery(query);
            if (rs.last()){
                String userid=rs.getString("username");
                userlb.setText("Welcome Dear "+userid);
                //userlbl1.setText(userid);                              
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "error");
            System.err.println(e);
        }

    }//GEN-LAST:event_formWindowActivated

    private void packActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packActionPerformed
        // TODO add your handling code here:
        String Pack=(String)pack.getSelectedItem();
        if(Pack.equals("Customised Packages"))
        {            new Booking().setVisible(true);
             //jLabel6.setVisible(false);
             combox.setVisible(false);             
             memlbl.setVisible(false);
             memtxt.setVisible(false);
             jButton1.setVisible(false);
             minus.setVisible(false);
             plus.setVisible(false);
        }
         else    if (Pack.equals("Packages"))
         {   packlb.setVisible(true);
             combox.setVisible(true);             
             memlbl.setVisible(true);
             memtxt.setVisible(true);
             jButton1.setVisible(true);             
         }

    }//GEN-LAST:event_packActionPerformed

    private void comboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxActionPerformed
        // TODO add your handling code here:
         String combopack=(String) combox.getSelectedItem();
        if (combopack.equals("Family Combo"))
        {
            memtxt.setVisible(true);
            amttxt.setVisible(true);
            amtlbl.setVisible(true);
            memlbl.setVisible(true);
            minus.setVisible(false);
                plus.setVisible(false);
            memtxt.setText("6");
            amttxt.setText("23000");
            
        }
        
        else if (combopack.equals("College Days"))
        {
            memtxt.setVisible(true);
            amttxt.setVisible(true);
            memlbl.setVisible(true);
            amtlbl.setVisible(true);  
            minus.setVisible(false);
                plus.setVisible(false);
            memtxt.setText("5");
            amttxt.setText("17000");
        }
        else if (combopack.equals("You Are The King"))
        {
                memtxt.setVisible(true);
                amttxt.setVisible(true);
                memlbl.setVisible(true);
                amtlbl.setVisible(true);
                minus.setVisible(true);
                plus.setVisible(true);
                memtxt.setText("1");
                amttxt.setText(""+5000);
            
        }

    }//GEN-LAST:event_comboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amtlbl;
    private javax.swing.JTextField amttxt;
    private javax.swing.JComboBox combox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel memlbl;
    private javax.swing.JTextField memtxt;
    private javax.swing.JButton minus;
    private javax.swing.JComboBox pack;
    private javax.swing.JLabel packlb;
    private javax.swing.JButton plus;
    private javax.swing.JLabel userlb;
    // End of variables declaration//GEN-END:variables
}
